#!/usr/bin/env node
/**
 * GitHub Secrets Synchronization Utility
 * 
 * Reads .env.local and uploads each key-value pair to GitHub Actions secrets
 * via the `gh` CLI. Also sets mandatory secrets.
 * 
 * Prerequisites:
 *   - `gh` CLI installed and authenticated
 *   - .env.local present in project root
 *   - .temp_b64.txt generated by convert-sa-to-b64.mjs
 * 
 * Usage: node scripts/sync-secrets.js
 */

const { readFileSync, existsSync } = require('fs');
const { execSync } = require('child_process');
const { resolve, join } = require('path');

const ROOT = resolve(__dirname, '..');
const ENV_FILE = join(ROOT, '.env.local');
const B64_FILE = join(ROOT, '.temp_b64.txt');

// ── Helpers ──────────────────────────────────────────────────────

function setSecret(name, value) {
    try {
        // Pipe value via stdin to avoid shell escaping issues with special chars
        execSync(`echo ${JSON.stringify(value)} | gh secret set ${name}`, {
            cwd: ROOT,
            stdio: ['pipe', 'pipe', 'pipe'],
        });
        console.log(`  ✅ ${name}`);
    } catch (err) {
        console.error(`  ❌ ${name}: ${err.message}`);
    }
}

function setSecretFromFile(name, filePath) {
    try {
        execSync(`gh secret set ${name} < "${filePath}"`, {
            cwd: ROOT,
            stdio: ['pipe', 'pipe', 'pipe'],
            shell: true,
        });
        console.log(`  ✅ ${name} (from file)`);
    } catch (err) {
        console.error(`  ❌ ${name}: ${err.message}`);
    }
}

// ── Main ─────────────────────────────────────────────────────────

function main() {
    console.log('🔄 Syncing secrets to GitHub Actions...\n');

    // 1. Parse .env.local
    if (!existsSync(ENV_FILE)) {
        console.error('❌ .env.local not found. Create it first.');
        process.exit(1);
    }

    const envContent = readFileSync(ENV_FILE, 'utf-8');
    const envLines = envContent
        .split('\n')
        .map(l => l.trim())
        .filter(l => l && !l.startsWith('#'));

    console.log('── .env.local secrets ──');
    for (const line of envLines) {
        const eqIdx = line.indexOf('=');
        if (eqIdx === -1) continue;

        const key = line.substring(0, eqIdx).trim();
        const val = line.substring(eqIdx + 1).trim();

        if (!key || !val) continue;
        setSecret(key, val);
    }

    // 2. Mandatory: BACKUP_ARCHIVE_PASSWORD
    console.log('\n── Mandatory secrets ──');
    setSecret('BACKUP_ARCHIVE_PASSWORD', 'MAStif55vova');

    // 3. Firebase Service Account Base64 (from file to avoid shell escaping)
    if (existsSync(B64_FILE)) {
        setSecretFromFile('FIREBASE_SERVICE_ACCOUNT_BASE64', B64_FILE);
    } else {
        console.warn('  ⚠️  .temp_b64.txt not found. Run convert-sa-to-b64.mjs first.');
    }

    console.log('\n✅ Sync complete!');
}

main();
